apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgresql
  name: postgresql
  namespace: ory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgresql
    spec:
      containers:
      - image: postgres:13
        name: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: ory
        - name: POSTGRES_PASSWORD
          value: orypass
        - name: POSTGRES_DB
          value: orydb
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgresql
  name: postgresql
  namespace: ory
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresql
  type: NodePort